name: Build Movies Zip

on:
  schedule:
    - cron: "0 * * * *"  
  workflow_dispatch:   

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Create kaggle.json
        run: |
          mkdir -p ~/.config/kaggle
          echo "$KAGGLE_JSON" > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit movies.zip only
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          echo "movies.json" >> .gitignore

          git add movies.zip .gitignore

          if ! git diff --cached --quiet; then
            git commit -m "Update movies.zip [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
